scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 30s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "app-server-node-exporter"
    scrape_interval: 10s
    static_configs:
      - targets:
          - "${REMOTE_APP_SERVER_HOST}:9100"

  - job_name: "app-server-cadvisor"
    scrape_interval: 10s
    static_configs:
      - targets:
          - "${REMOTE_APP_SERVER_HOST}:8081"

  - job_name: "app-server-main-app"
    scrape_interval: 15s
    static_configs:
      - targets:
          - "${REMOTE_APP_SERVER_HOST}:8080"
